baseURL = "https://sijmenschoon.nl/"
languageCode = "en-us"
title = "sijmenschoon.nl"
theme = "hugo-coder"
publishDir = "docs"

[params]
author = "Sijmen Schoon"
info = "Developer"
keywords = "developer,personal"
avatarurl = "images/avatar.jpg"

hidecredits = true
hidecopyright = true

custom_css = ["css/style.css"]

[[params.social]]
name = "GitHub"
icon = "fa fa-github fa-2x"
weight = 1
url = "https://github.com/vijfhoek/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-linkedin fa-2x"
weight = 2
url = "https://www.linkedin.com/in/sijmen-/"

[[params.social]]
name = ""
icon = "fa fa-envelope fa-2x"
weight = 3
url = "mailto:info@sijmenschoon.nl"
